name: Extract CSVs from Hindalco PDF

on:
  workflow_dispatch:
  schedule:
      - cron: '0 11 * * *'  # Run at 4:30 PM IST daily

jobs:
  extract_csvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install PyPDF2

      - name: Extract CSV from PDF
        run: |
          python csv_from_pdf.py

      - name: Commit CSV Updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ls csv/*.csv 1> /dev/null 2>&1; then
            git add csv/*.csv
            git commit -m "Updated CSVs from latest Hindalco PDF"
            git push
          else
            echo "No CSVs to commit."
          fi

